url: https://sanchitjekylltheme.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: TEJ20R Portfolio
email: khope.sanchit@gmail.com
description: " Hello there, I am Sanchit Khope, a Mississauga-based Grade 10 student studying at Port Credit Secondary School. I am  passionate about exploring new concepts and turning them into physical projects that I can share with the world. Whether it's through coding traffic sequences, designing chess pieces, or presenting my thoughts in general, I enjoy the process of bringing my ideas to life. Beyond academics, I constantly seek inspiration through creative sources. Here is a quote that truly inspires me and keeps me motivated every day."


# Team names, titles and social links
people:
- name: Sanchit Khope
  pic: 1
  position: Student
  
# Build settings
markdown: kramdown
permalink: pretty
